# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Locktrip' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Locktrip

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on 

  target 'LocktripTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
